spring.application.name=ChikenPIX

spring.datasource.url=jdbc:postgresql://localhost:5432/chickenpix
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true